language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - wget http://get.sensiolabs.org/php-cs-fixer.phar

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text
  - php php-cs-fixer.phar fix -v --dry-run
